### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by henrymartin262** [bata24/gef#100]
<img width="904" alt="Snipaste_2024-12-21_23-21-04" src="https://github.com/user-attachments/assets/c0f3a656-84ae-4443-b667-8324b944e943" />
hello, I meet err when I try to execute command "ksymaddr-remote commit_creds"

**Comment by bata24** [comment]
Thank you for reporting this issue.

It may be that the information of `kallsyms` parsing failed.
Please provide a kernel image (`vmlinuz` or `bzImage`, etc.) and `run.sh` for reproducing.

**Comment by henrymartin262** [comment]
<img width="722" alt="Snipaste_2024-12-22_10-14-30" src="https://github.com/user-attachments/assets/282dd4ff-8cc7-48a8-ab9e-04a134baec01" />
<img width="599" alt="Snipaste_2024-12-22_10-14-42" src="https://github.com/user-attachments/assets/e545f6cc-cefe-4de4-8178-a5ff18ce2f90" />
Sure, there are details about this err. Please tell me If you need more information about it.

**Comment by bata24** [comment]
I tried using kernel 6.12.6, but the kernel wouldn't start properly and it took a long time.

I wrapped it in a `try-catch` to ignore the index error.
Could you try it in this state and see what happens?

If that doesn't improve it, could you provide me with a kernel image (via Google Drive or a suitable uploader)?

**Comment by henrymartin262** [comment]
<img width="678" alt="Snipaste_2024-12-23_08-02-48" src="https://github.com/user-attachments/assets/1dfdd3eb-029b-484c-8c00-89e32902feb4" />
Thanks very much, I wrap it in a `try-catch` and see the symbol addr.

**Comment by bata24** [comment]
That's good to hear.

It has been reflected in the latest version of GEF.
I'll close the issue for now.
