### ISSUE TITLE
`heap` command failed after detach and attach new process

### ISSUE THREAD

**Issue by Chovid99** [bata24/gef#53]
Hi, I was currently playing around with your extension (which is super awesome), but I noticed small issues with it that I would like to report so that it can get better.

Let say that I start a new process A, and attach it to the current gdb session. If I detach, start a new process (B), and attach the new process, the `heap` command will be broken.

I suspect that there might be some cache not cleared during detaching a process, which caused the `main_arena` value is wrong. 
Step by step to reproduce:
- Start new process 123
- `attach 123`
- `heap bins` (work successfully)
- `detach`
- Start new process 321
- `attach 321`
- `heap bins` (broken with error message `"Failed to get the arena, heap commands may not work properly."`).

Currently, the workaround is I need to do `gef reload` to reset it, but `gef reload` is quite slow. It would be great if this small issue can be fixed. Thanks a lot for creating this amazing extension!

**Comment by bata24** [comment]
Thank you for the report.
My debugging style is to quit and restart gdb each time, so I didn't notice this problem.

To fix the problem, I added processing to clear the `heap_base cache` and `main_arena cache` to `reset_gef_cache`.
See: 44fb1bd0e5e12295df99b2dbdfe8138ba64024c0

**Comment by Chovid99** [comment]
Thanks a lot for the quick response, I just tested it and it works perfectly! Really appreciate for the creation and maintenance of this awesome extension!
