### ISSUE TITLE
slub-dump command is slow, can make a progress bar or others for it

### ISSUE THREAD

**Issue by xrivendell7** [bata24/gef#6]
version

```sh
gef> version
---------------------------------------------------------------- versions ----------------------------------------------------------------
OS:                     Ubuntu 22.04.2 LTS
kernel (uname -a):      Linux xxx 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
kernel (/proc/version): Linux version 5.19.0-41-generic (buildd@lcy02-amd64-045) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2
qemu:                   8.0.0
GEF:                    Last modified: 2023-06-26 19:59:30 SHA1: 4edc0048aa40cedf5e92f49c9c6fea7944ea54b8
gdb:                    12.1
python:                 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
capstone:               5.0.1280
keystone:               0.9.9
unicorn:                2.0.1
ropper:                 1.13.8
gcc:                    gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
readelf:                GNU readelf (GNU Binutils) 2.40
objdump:                GNU objdump (GNU Binutils) 2.40
seccomp-tools:          SeccompTools Version 1.5.0
one_gadget:             OneGadget Version 1.8.1
```
archinfo: i386:x86-64
file : "/home/xxx/linux/vmlinux" about 1.8G
gef commit 1cf39978728668a55b9b62b51030cdc8299e203e

Since vmlinux is sometimes really huge to analysis, slub-dump command most of the time run slower, can add a progress bar for the searching commands? or I can realize that this command was not slow but stuck or something.

I often run the command when running like that

```sh
gef> slub-dump xfrm_state
[+] Wait for memory scan
^C
^C^C^CQuit
gef> slub-dump
[+] Wait for memory scan
^C^C^C^C^C^C^C^C^C^C^C^C^C

^C
^C^C^C

^C
^C
^C
^C
^C
^C
^C
^C
^C

```
I really don't know the progress and don't know if I should wait or not.

**Comment by xrivendell7** [comment]
Oh. It may because my vmlinux version is 6.4.0-rc7. It cause `ksymaddr-remote` failed to get the symbol address.

```sh
------------------------------------------------------------------------------------------ source:./arch/x86/include/asm/irqflags.h+37 ----
     32         return flags;
     33   }
     34
     35   static __always_inline void native_irq_disable(void)
     36   {
 ->  37         asm volatile("cli": : :"memory");
     38   }
     39
     40   static __always_inline void native_irq_enable(void)
     41   {
     42         asm volatile("sti": : :"memory");
-------------------------------------------------------------------------------------------------------------------------------- stack ----
0xffffffff84e03e80|+0x0000|000: 0xffffffff8395b8cd <default_idle_call+0x7d>  ->  0xffe18ae8243c8b48  <-  retaddr[1]  <-  $rsp
0xffffffff84e03e88|+0x0008|001: 0xffffffff8125f1b6 <do_idle+0x1e6>  ->  0x65803effffff26e9  <-  retaddr[2]
0xffffffff84e03e90|+0x0010|002: 0xffff88823fffd040  ->  ' nokaslr page_owner=on spec_store_bypass_disable=prctl'
0xffffffff84e03e98|+0x0018|003: 0x733d280fa04abe00
0xffffffff84e03ea0|+0x0020|004: 0xffff88823fffd076  ->  0x0000000000000000 <fixed_percpu_data>
0xffffffff84e03ea8|+0x0028|005: 0x00000000000000eb
0xffffffff84e03eb0|+0x0030|006: 0xffff88823fffd040  ->  ' nokaslr page_owner=on spec_store_bypass_disable=prctl'
0xffffffff84e03eb8|+0x0038|007: 0x0000000000000000 <fixed_percpu_data>
-------------------------------------------------------------------------------------------------------------------------------------------
gef> ksymaddr-remote commit_creds
gef>
```

However, I can get the symbol address in the qemu with `/proc/kallsyms` since KASLR is disalbe
```sh
root@syzkaller:~# cat /proc/kallsyms  |grep commit_creds
ffffffff8122f2e0 T commit_creds
ffffffff84b99fc0 r __ksymtab_commit_creds
```

The failed of the `ksymaddr-remote` cause get `get_slab_type` return SLUB_TINY that it's wrong and when I try the command `slub-dump` is stunk or show this

```sh
gef> slub-dump
[+] Wait for memory scan
[!] Unsupported SLAB, SLOB, SLUB_TINY
gef> slob-dump
[+] Wait for memory scan
[!] Unsupported SLUB, SLAB, SLUB_TINY
```

may consider to check and fix the command `ksymaddr-remote`
I also check another kernel version 6.2.0-rc7, the command run correctly

**Comment by bata24** [comment]
Thanks for reporting the problem and finding the cause.
Maybe kernel 6.4 changed the structure of kallsyms again (?)
I will now examine their structure.

**Comment by xrivendell7** [comment]
@bata24 
Cause I'm not familiar with how to debug gef.py script, I upload my [envirnment](https://drive.google.com/file/d/1M0FfllRs9BL6pvf9Y30WAoIsXjA_YsJT/view). It's may help you qucik find the problem.

**Comment by bata24** [comment]
The structure of kallsyms was different. My assumption was the following:
```
kallsyms_offsets
kallsyms_num_syms
kallsyms_names
kallsyms_markers
kallsyms_seqs_of_names
kallsyms_token_table
kallsyms_token_index
```
However, in the kernel you provided, it looks like this:
```
kallsyms_num_syms
kallsyms_names
kallsyms_markers
kallsyms_seqs_of_names
kallsyms_token_table
kallsyms_token_index
kallsyms_offsets (<--- weird)
```
Another tool, vmlinux-to-elf, also assumes the former structure, and this sequence seems quite peculiar.
I'll do some more research to see if this is a specific structure of this kernel or if it's changed since v6.4.

**Comment by bata24** [comment]
It was fixed. See commit d0e563b21ee440489927d7124a4b71199526a552.

```
gef> ks commit_creds -r -v
[+] Wait for memory scan
[+] krobase: 0xffffffff83c00000-0xffffffff84c63000
[+] linux_banner: 0xffffffff83c00100
[+] kallsyms_token_table: 0xffffffff844f9dc0
[+] kallsyms_token_index: 0xffffffff844fa178
[+] kallsyms_markers_table_element_size: 0x4
[+] kallsyms_markers: 0xffffffff844f8b78
[+] kallsyms_seqs_of_names: 0xffffffff844f9dbc
[+] kallsyms_names: 0xffffffff841507e4 (candidate)
[+] num_symbols: 0x49039
[+] kallsyms_names: 0xffffffff84150570
[+] kallsyms_num_syms: 0xffffffff84150568
[+] kallsyms_offsets: 0xffffffff844fa378
0xffffffff8122f2e0 T commit_creds
0xffffffff84b99fc0 r __ksymtab_commit_creds
gef> 
```

```
gef> slub-dump -n kmalloc-256
[+] Wait for memory scan
--------------------------------------------------------------------------- CPU 0 ---------------------------------------------------------------------------
slab_caches @ 0xffffffff85000ab0

  kmem_cache: 0xffff888008841900
    name: kmalloc-256
    flags: 0x40001000 (__CMPXCHG_DOUBLE | SLAB_KMALLOC)
    object size: 0x100 (chunk size: 0x100)
    offset (next pointer in chunk): 0x80
    kmem_cache_cpu (cpu0): 0xffff88800f8335e0
      active page: 0xffffea000002a780
        virtual address: 0xffff888000a9e000
        num pages: 1
        in-use: 3/16
        frozen: 1
        layout:   0x000 0xffff888000a9e000 (in-use)
                  0x001 0xffff888000a9e100 (in-use)
                  0x002 0xffff888000a9e200 (in-use)
                  0x003 0xffff888000a9e300 (next: 0xffff888000a9e400)
                  0x004 0xffff888000a9e400 (next: 0xffff888000a9e500)
                  0x005 0xffff888000a9e500 (next: 0xffff888000a9e600)
                  0x006 0xffff888000a9e600 (next: 0xffff888000a9e700)
                  0x007 0xffff888000a9e700 (next: 0xffff888000a9e800)
                  0x008 0xffff888000a9e800 (next: 0xffff888000a9e900)
                  0x009 0xffff888000a9e900 (next: 0xffff888000a9ea00)
                  0x00a 0xffff888000a9ea00 (next: 0xffff888000a9eb00)
                  0x00b 0xffff888000a9eb00 (next: 0xffff888000a9ec00)
                  0x00c 0xffff888000a9ec00 (next: 0xffff888000a9ed00)
                  0x00d 0xffff888000a9ed00 (next: 0xffff888000a9ee00)
                  0x00e 0xffff888000a9ee00 (next: 0xffff888000a9ef00)
                  0x00f 0xffff888000a9ef00 (next: 0x0)
        freelist: 0x003 0xffff888000a9e300
                  0x004 0xffff888000a9e400
                  0x005 0xffff888000a9e500
                  0x006 0xffff888000a9e600
                  0x007 0xffff888000a9e700
                  0x008 0xffff888000a9e800
                  0x009 0xffff888000a9e900
                  0x00a 0xffff888000a9ea00
                  0x00b 0xffff888000a9eb00
                  0x00c 0xffff888000a9ec00
                  0x00d 0xffff888000a9ed00
                  0x00e 0xffff888000a9ee00
                  0x00f 0xffff888000a9ef00
    next: 0xffff888008841800
gef> 
```

**Comment by bata24** [comment]
Kernel v6.4.2 built in my environment had the same structure. Probably, I think it will be this structure from v6.4.
However, I couldn't find any changes in the source code that would cause it, so it may be the compiler's fault.

**Comment by xrivendell7** [comment]
Yes, I'm sure in my provided vmlinux, it's run normally.

**Comment by xrivendell7** [comment]
However, I think when the `slub-dump` command runs abnormally, It should quick throw a error/warn or something. When It's stuck at `[+] Wait for memory scan` I can't really sure about It's run corret or not. Maybe check at the very begining is better?.

**Comment by bata24** [comment]
Yes, `get_slab_type` and `kernel_version` were also fixed.
See commits d12f8ca481d609956b2c762214a2edaf1c249ba6 and fe96e5c8e5a5dddb6c90e6ae99933bb37cbfe629.
These are dirty patch, but maybe it works.

**Comment by xrivendell7** [comment]
Really appreciate your work and very fast response. Thanks!

**Comment by DeathNet123** [comment]
The issue is closed but i am facing the same `unsupported SLAB, SLOB, SLUB_TINY` 

I checked the version 6.1.66 and 6.10.11 it throws the same error on both.

**Comment by bata24** [comment]
Could you please provide the kernel image you are having trouble with, and the qemu boot command (`run.sh`)?

**Comment by DeathNet123** [comment]
Hey, this is the environment for the kernel version 6.10.11 [Environment](https://drive.google.com/drive/folders/1z8BoWB7wpiPzhvOaYng3J0cTolu2yw79?usp=sharing) 

I have also attached the config file just in case if there is requirement for configuration.

**Comment by bata24** [comment]
Thank you, I'll take a look at it tonight.

**Comment by bata24** [comment]
I tried running the `slub-dump` command in the environment you provided, and **it seems to work without any problems**.
(I used a file system image that I created. I tried it several times while restarting qemu-system.)

I recently changed the `kernel base` detection logic, so I thought that might be affecting it, but it seems to work even with a GEF 1 year ago.

Let me check a few things again.
- Does the same problem occur with the latest GEF?
- Are you using `slub-dump`, `slab-dump`, `slob-dump`, and `slub-tiny-dump` correctly?
- It may not be a problem with `slub-dump`, but with `ksymaddr-remote`. Does the `ks` command work correctly?
- If you rename the config file (`/root/.gef.rc`) and no longer use it, does it change the behavior?
- Try deleting the cache (`/tmp/gef`).
- Are you running on a very old environment? (Ubuntu 24.04 is fine)

----
Although I have just made some modifications to slub-dump (5509d2a4d2dc1f7b6af1e80bd5659d03f77defa3), this only add options to display only partial pages or node pages. This change is not directly related to this issue.

**Comment by DeathNet123** [comment]
- I have tried using the latest GEF. The issue remains
- ks command is not working properly in fact the buddy-dump seems to stop working too
- renaming the `.gef.rc` doesn't effect anything
- I have deleted the `/tmp/gef` it didn't help much 
- I am on 22.04.3-Ubuntu version

**Comment by bata24** [comment]
The cause was found and the fix was complete. See e037fa36a0348a0e30f91965e1b8d4b67e30d34f.
The cause was that GEF was not detecting `kallsyms_seqs_of_names`.

I thought that the structure `kallsyms_seqs_of_names` was introduced from 6.2, but to be precise, it was introduced from 6.1.42.
Since GEF only detected this structure from 6.2 onwards, an error occurred in 6.1.66.

I tested it with the 6.1.44 and 6.1.55 kernels, but `ksymaddr-remote` worked even without detecting `kallsyms_seqs_of_names`, so I was unable to notice.

**Comment by DeathNet123** [comment]
Yikes, Really appreciate your work. It's working on the `kernel version 6.1.66` too now
