### ISSUE TITLE
Heap commands break for older glibc versions

### ISSUE THREAD

**Issue by programmeruser2** [bata24/gef#74]
Even after allocating a chunk inside this program that uses glibc 2.23 `heap chunks` states that the heap hasn't been initialized. hugsy/gef seems to work correctly so I'm not sure what's going wrong here

**Comment by programmeruser2** [comment]
[Uploading sice_cream.zip…]()

**Comment by programmeruser2** [comment]
[sice_cream.zip](https://github.com/bata24/gef/files/14936266/sice_cream.zip)

**Comment by bata24** [comment]
Thank you for your reporting.

It was fixed. See 7f1940752f6452f643292027a1cd4a7a6a8be0f6 and try latest.
I haven't tested with the old glibc for a while, so I didn't notice it was degraded. Sorry.
