### ISSUE TITLE
Failed to find kallsyms_names in 6.9.0-rc2

### ISSUE THREAD

**Issue by xrivendell7** [bata24/gef#75]
Hello.

I found it failed to execute ks in this kernel, but I'm not analysis depthly.

```
gef> ks -r -v
[+] Wait for memory scan
[+] ro_base: 0xffffffff84400000-0xffffffff858a0000
[+] linux_banner: 0xffffffff844000e0
[+] unique_bytes: 0xffffffff84fcab5d
[+] kallsyms_token_table: 0xffffffff84fcaa88
[+] kallsyms_token_index: 0xffffffff84fcae38
[+] kallsyms_markers_table_element_size: 0x4
[+] kallsyms_markers: 0xffffffff84fc8d70
[+] kallsyms_seqs_of_names: 0xffffffff84fcaa8c
[+] kallsyms_names: 0xffffffff84982804 (candidate)
[+] Could not find kallsyms_names
[+] ro_base: 0xffffffff84400000-0xffffffff858a0000
[+] linux_banner: 0xffffffff844000e0
[+] unique_bytes: 0xffffffff84fcab5d
[+] kallsyms_token_table: 0xffffffff84fcaa88
[+] kallsyms_token_index: 0xffffffff84fcae38
[+] kallsyms_markers_table_element_size: 0x4
[+] kallsyms_markers: 0xffffffff84fc8d70
[+] kallsyms_seqs_of_names: 0xffffffff84fcaa8c
[+] kallsyms_names: 0xffffffff84982804 (candidate)
[+] Could not find kallsyms_names
[+] Failed to parse.
```
It's failed in `find_kallsyms_num_syms`
```
        while True:
            if position < 0:
                self.verbose_err("Could not find kallsyms_names")
                return False
```

I public [bzImage](https://www.dropbox.com/scl/fi/grl9u7fhufa5ay4evhvx1/bzImage666?rlkey=jj9yg2f50rgyl1uyicy03e42w&dl=0) and [vmlinux](https://www.dropbox.com/scl/fi/jyk8gi8pjkv7vh6nutupk/vmlinux666?rlkey=458od7xncde3n6a2js7pgb5gy&dl=0) for deubgging as usual.

**Comment by xrivendell7** [comment]
The fail execute of the command `ks` cause almost all the kernel related command failed.

**Comment by bata24** [comment]
Thank you for always reporting.

I haven't confirmed whether it works properly on Linux 6.9 yet.
I'll check it tonight.

**Comment by bata24** [comment]
It was fixed. See 2228dd158f0a479591c41a6ed5049f23105eac4d.

The root cause was that the location of `kallsyms_seqs_of_names` had moved.

**Comment by xrivendell7** [comment]
Hi, I comfired it fixed in my enviroment. Thanks.
