### ISSUE TITLE
Fix incompatibility with silent auto-continuing on breakpoint

### ISSUE THREAD

**Issue by xairy** [bata24/gef#76]
Silent auto-continuing on a breakpoint (see the example commands below) makes the screen flicker (I guess because of the UI redrawing) instead of the expected printing of the RAX value into the log every time the breakpoint gets hit (this is what happens with GDB without GEF).

```
(gdb) b *0xdeadbeef
Breakpoint 1 at 0xdeadbeef
(gdb) commands
Type commands for breakpoint(s) 1, one per line.
End with a line saying just "end".
>silent
>p/x $rax
>c
>end
(gdb) c
```

**Comment by bata24** [comment]
Thank you for reporting.

I've reproduced the problem, but I can't figure out how to fix it yet.
I'm considering using gdb events to determine this within the hook function.

As a workaround, you can run `context off` to temporarily turn off the screen output.

**Comment by bata24** [comment]
It was fixed. See 7b2967f629241d939230c18e1b17a4da26fd3ca6.

Fundamentally, it is determined whether the command associated with the currently stopped breakpoint starts with `silent`.

However, there were many other problems.
The process executed within `hook_stop_handler` was reviewed and fixed.
`ni`, `si` and `c` wrapper were also fixed.

**Comment by xairy** [comment]
Awesome, works perfectly now, thanks a lot for the quick fix!
