### ISSUE TITLE
`heap-analysis-helper` is broken on Ubuntu24.04

### ISSUE THREAD

**Issue by bata24** [bata24/gef#78]

**Comment by bata24** [comment]
In Ubuntu 24.04 (glibc 2.39), it seems that there are cases where gdb is unable to catch the timing when `realloc` or `malloc` returns.
It can be caught using `out_of_scope`, but it cannot identify the allocated address, and therefore it is not possible to continue tracing.
I thought this was impossible to fix, so I added that to the help message.

**Comment by MrRtcl** [comment]
Sometimes gdb.FinishBreakpoint can't catch return of functions....
I think that using gdb.Breakpoint and  gdb.newest_frame().older().pc() to catch result will solve this bug.

**Comment by bata24** [comment]
Thank you for your comment.

In the latest GEF version, the `heap-analysis-helper` command has been removed. This was because there was no prospect of fixing the bug, so I wanted to prevent confusion caused by GEF users using it incorrectly.

The same thing can be done with the following tool, so it is safer to use it.
https://github.com/Arinerron/heaptrace

However, it seems possible to achieve this if we use `gdb.Breakpoint` instead of `gdb.FinishBreakpoint`. I will consider restoring the deleted this command :)

**Comment by MrRtcl** [comment]
> Thank you for your comment.
> 
> In the latest GEF version, the `heap-analysis-helper` command has been removed. This was because there was no prospect of fixing the bug, so I wanted to prevent confusion caused by GEF users using it incorrectly.
> 
> The same thing can be done with the following tool, so it is safer to use it. https://github.com/Arinerron/heaptrace
> 
> However, it seems possible to achieve this if we use `gdb.Breakpoint` instead of `gdb.FinishBreakpoint`. I will consider restoring the deleted this command :)

I missed the same bug on `kmalloc-tracer` command  :). And I found this method while trying to solve the problem (

**Comment by bata24** [comment]
`kmalloc-tracer` was fixed (replaced `gdb.FinishBreakpoint` to `gdb.Breakpoint`).
`heap-analysis-helper` was revival (with `gdb.Breakpoint` but without `gdb.FinishBreakpoint`).
