### ISSUE TITLE
check for pagewalk command maybe slow in linux kernel 6.1.0+

### ISSUE THREAD

**Issue by xrivendell7** [bata24/gef#8]
Hi, bata24
I meet a problem with debugging with kernel 6.1.0
When I run command such as `kbase` `kcurrent` `vmmap` it runs with the output and stuck for about 30 minus without showing the right answer.

```c
gef> kcurrent
[+] Wait for memory scan
















^C^C^C^C^C^C
^C^C

^C
^C
^C
^C
^C
^C
Quit
gef>
gef> kbase
[+] Wait for memory scan
^C^C^C^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
^C
Quit
gef>
gef> kmagic
[+] Wait for memory scan
^C^C^C^C

^C
^C
^C
^C
^C
^C
^C
^C

^C
^C
^C^C^C^C^C^C^C^C^C
^CQuit
```
Since It's unusual slow and I do not know it stuck or not and these commands based on pagewalk, it maybe the pagewalk command slow. As usual, I upload my environment to gcd and support for you to check it. https://drive.google.com/file/d/1iEpaZbVCPtitSXAv5NW9iewo6EY_zExb/view?usp=sharing

**Comment by bata24** [comment]
Thanks to report. I'll check what happend.
The Google Drive link doesn't seem to have access rights. Could you please make it public?

**Comment by xrivendell7** [comment]
I have update the link https://drive.google.com/file/d/1iEpaZbVCPtitSXAv5NW9iewo6EY_zExb/view 
and It seems the memory-scan cause a OOM

```sh
gef> slub-dump
[+] Wait for memory scan
[1]    172142 killed     gdb -iex "add-auto-load-safe-path ./" vmlinux
```

**Comment by bata24** [comment]
I aborted `pagewalk` 's parse and dumped it, and it seems that there are a lot of entries starting with 0xffffec0XXXXXX000 pointing to the same physical memory address.
```
0xffffec0000***000-0xffffec0000***000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00010**000-0xffffec00010**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00011**000-0xffffec00011**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00012**000-0xffffec00012**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00013**000-0xffffec00013**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00014**000-0xffffec00014**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00015**000-0xffffec00015**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00016**000-0xffffec00016**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00017**000-0xffffec00017**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00018**000-0xffffec00018**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec00019**000-0xffffec00019**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec0001a**000-0xffffec0001a**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
0xffffec0001b**000-0xffffec0001b**000  0x00000000056e8000-0x00000000056e9000  0x1000       0x1000      1      [R-- KERN ACCESSED DIRTY]
```

I'm not very familiar with this area, but from its address I think it's probably KASAN Shadow Memory.
I added code to skip parsing this area, and confirmed that the parsing completed without OOM. See f7965f4e26218671d7f740168f8f75adb82c69c8 .
Also the problem of `pagewalk` taking a long time has been solved.

However, the problem that `kbase` cannot solve is still not resolved. I will investigate further.

**Comment by bata24** [comment]
The problem is fixed. See 526490219ee24173b9217811ca69c7190d64a698 .
The root cause has been identified. It seems to have been degraded with the following commit. Sorry.
- 8dffc4d1a46fe1ca0dae3c0e0705256f9f2c9e8a
- 9f24078201e4df389f8b23c417cdf2a0676ff469
- ad21a7347b49fb90e79f606f6a2ee30795f105a0

**Comment by xrivendell7** [comment]
I confirm the problem solved in my environment. Thanks.
