### ISSUE TITLE
issue in `read_remote_file` indirectly causing failure to resolve libc version

### ISSUE THREAD

**Issue by unvariant** [bata24/gef#86]
```c
def read_remote_file(filepath, as_byte=True):
    tmp_name = os.path.join(GEF_TEMP_DIR, "read_remote_file.tmp")
    try:
        gdb.execute("remote get {:s} {:s}".format(filepath, tmp_name), to_string=True)
    except gdb.error:
        return ""
```

`filepath` is passed as-is into the gef command, and if the filepath contains spaces the command fails since it reads the wrong number of arguments. I discovered this issue while debugging the heap commands thinking safe-linking was enabled on libc 2.31, turns out it was failing to read libc because my pwd contained spaces.

**Comment by bata24** [comment]
Thanks for reporting. I enclosed them in single quotes.

I know that an error occurs when the path contains a single quote.
However, I can't think of a uniform and clean way to fix it, so I'll postpone fixing it.
At least it shouldn't be degraded.

**Comment by bata24** [comment]
I found that the `"{!r}".format(path)` format worked well, so I rewrote it. Close.
