### ISSUE TITLE
question/feat request: easy way to check permissions of virtual address

### ISSUE THREAD

**Issue by k4lizen** [bata24/gef#90]
Currently when looking for rop gadgets I have to often go back and forth and check whether the address of the gadget is actually executable in the debugger. I don't know if there's an easier way but currently I do that with
`gef> pw --trace <vaddr>`
but typing `--trace` every single time is quite cumbersome when I would hope something like
`gef> pw <vaddr>`
or even
`gef> vmmap <vaddr>`
would work.

Also there's a lot of extraneous info that gets printed that I don't care about for this usecase, but that's not as much of an issue.

**Comment by bata24** [comment]
Thanks for your question.
I think, how about using `xinfo <vaddr>` ?
It also supports qemu-system, so I think it can check permissions and calculate offsets.

**Comment by k4lizen** [comment]
A that works! Thanks!
