### ISSUE TITLE
" in f-string cause crash on  < python3.12 

### ISSUE THREAD

**Issue by GamrayW** [bata24/gef#94]
Installing the new version on a system without python3.12 (mine is 3.11.2), causes a crash when starting gdb and fails to start gef:

```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
  File "/home/gamray/.gdbinit-gef.py", line 88316
    pfn_str = f"0x{data["pfn"]:x}" if data["pfn"] != 0 else "0x0"
                         ^^^
SyntaxError: f-string: unmatched '['
Reading symbols from test...
(No debugging symbols found in test)
(gdb) 
``` 

Error is in `gef.py` L88316, simply using single quote instead of double quote make it work again :
`pfn_str = f"0x{data['pfn']:x}" if data["pfn"] != 0 else "0x0"`

I don't know if I should do a pr for such a little thing but I fixed it like this on my machine.

**Comment by tramasys** [comment]
Ah yes, introduced by my PR: https://github.com/bata24/gef/pull/93
I forgot that embedded expressions in CPython's f-string impl. before `3.12` cannot contain any arbitrary expression (double quotes). As you said, reverting to single quotes fixes this for versions < `3.12`.
My bad! 🤦🏼

**Comment by bata24** [comment]
It was fixed. Try latest :)

**Comment by GamrayW** [comment]
Works good now, thanks ! 👍
