### ISSUE TITLE
The search strategy of the find_kallsyms_markers function may be incorrect.

### ISSUE THREAD

**Issue by Polaris-Snowfall** [bata24/gef#98]
I am encountering an issue where most commands related to kernel symbols don't work correctly on my kernel (v6.1.63). Debugging reveals that the problem is caused by an incorrect resolution of the location of kallsyms_markers. Upon reviewing the source code of the related search strategy, I found that an additional \x00\x00\x00\x00 sequence is causing the problem. This sequence is located at kallsyms_seqs_of_names - 4, and as shown in the diagram below, there are three such \x00\x00\x00\x00 sequences between kallsyms_markers and kallsyms_token_table, which leads to the incorrect parsing of kallsyms_markers.

![图片](https://github.com/user-attachments/assets/8ef1bcd6-44ca-4ca2-8a47-c522f809d087)

![图片](https://github.com/user-attachments/assets/11f06120-cf45-4377-9d90-bd3e72985cf0)

I tried to add a reverse search to address the issue, and it does solve the problem, but that should not be the correct solution.

One additional piece of information that might help with your maintenance: when I first compiled the 6.1.63 kernel, gef worked fine. However, when I enabled options like CONFIG_MEMCG and CONFIG_MEMCG_KMEM and recompiled the kernel, the issue appeared. Therefore, this is likely not specific to the 6.1.63 kernel version itself.

Here’s the relevant section of code that handles the search for kallsyms_markers:

```python
        # kallsyms_seqs_of_names is introduced from kernel 6.1.42
        # in this case, it finds kallsyms_seqs_of_names instead of kallsyms_markers, so search back through memory again.
        if self.kernel_version >= (6, 1, 42) and self.kernel_version < (6, 9, 0):
            if u32(self.kernel_img[needle + 4:needle + 8]) & 0xfff00000: # false positive, search again
                position = needle
                # aligned search from memory
                while position > 0:
                    needle = self.kernel_img.rfind(seq_to_find, 0, position)
                    if needle == -1:
                        self.verbose_err("Could not find kallsyms_markers")
                        return False
                    # check alignment
                    align_diff = needle % self.kallsyms_markers_table_element_size
                    if align_diff == 0:
                        break
                    position = needle + self.kallsyms_markers_table_element_size - align_diff

        # HanQi
        if self.kernel_version == (6, 1, 63):
            if u32(self.kernel_img[needle + 4:needle + 8]) & 0xfff00000: # false positive, search again
                position = needle
                # aligned search from memory
                while position > 0:
                    needle = self.kernel_img.rfind(seq_to_find, 0, position)
                    if needle == -1:
                        self.verbose_err("Could not find kallsyms_markers")
                        return False
                    # check alignment
                    align_diff = needle % self.kallsyms_markers_table_element_size
                    if align_diff == 0:
                        break
                    position = needle + self.kallsyms_markers_table_element_size - align_diff

        self.offset_kallsyms_markers = needle
        self.save_config("offset_kallsyms_markers")
        self.verbose_info("kallsyms_markers: {:#x}".format(self.ro_base + self.offset_kallsyms_markers))
```

Here is the relevant environment.
[env.zip](https://github.com/user-attachments/files/17657209/env.zip)

**Comment by bata24** [comment]
Thanks for reporting the issue. I have reproduced the problem.

When searching `kallsyms_seqs_of_names`, I noticed that in rare cases false positives could occur depending on the order of values ​​in memory.

So I decided to repeat the search for `kallsyms_seqs_of_names` multiple times if the condition is not met.
I think this should fix it.

**Comment by bata24** [comment]
I'll close this issue for now. Please feel free to reopen if necessary.
